import Header from "@/components/Header";
import "./globals.css";
import { Roboto } from "next/font/google";
import StyledComponentsRegistry from "./lib/registry";

const roboto = Roboto({ weight: ['400', '700'], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={roboto.className}>
          <Header></Header>
          {children}
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
