import "./globals.css";
import { Roboto } from "next/font/google";
import StyledComponentsRegistry from "./lib/registry";
import PageWrapper from "@/components/PageWrapper";

const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <PageWrapper roboto={roboto}>{children}</PageWrapper>
      </StyledComponentsRegistry>
    </html>
  );
}
